config/routes.rb
Rails.application.routes.draw do
  resources :orders_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_many :featured_products, -> { Product.featured }, class_name: 'Product', inverse_of: :category
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_items
  before_save :set_subtotal

  def subtotal
    orders_items.collect { |orders_item| orders_item.valid? ? orders_item.unit_price * orders_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # si hay un registro
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_one_attached :image
    scope :featured, -> { where(featured: true) }
    has_many :orders_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @orders_items = current_order.orders_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats
  
  def index
    @page = 'menu'
    @products = Product.all
    @orders_item = current_order.orders_items.new
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Filtrar por'
      @products = results
    else
      # 'Gluten Free' -> 'Gluten_Free' -> 'gluten_free' -> :gluten_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
      # @products = results.where(:gluten_free => true)
      # @products = results.where(symbol => true)
      @products = results.send(symbol)
                    
    end
  end

  private

  def set_cats
    @cats = Category.all.where(display: true)
  end
end

app/controllers/orders_items_controller.rb
class OrdersItemsController < ApplicationController
  before_action :set_order

  def create
    @orders_item = @order.orders_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @orders_item = @order.orders_items.find(params[:id])
    @orders_item.update_attributes(order_params)
    @orders_items = current_order.orders_items
  end

  def destroy
    @orders_item = @order.orders_items.find(params[:id])
    @orders_item.destroy
    @orders_items = current_order.orders_items
  end

  private

  def order_params
    params.require(:orders_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id, :dairy_free, :gluten_free, :vegan, :vegetarian, :available, :catering, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
      # Utilicé Find by id para evitar posibles errores
    #    @current_order ||= Order.find_by_id(session[:order_id]).presence || Order.new
      if Order.find_by_id(session[:order_id]).nil?
        Order.new
      else
        Order.find_by_id(session[:order_id])
      end
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_items_helper.rb
module OrdersItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.orders_items.size} artículos con un valor de: $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @orders_items.each do |item| %>
<h3><%= item.product.name%></h3>
<h3>$<%= item.product.price %></h3>
<%= form_with model: item do |f|%>
<%= f.hidden_field :product_id, value: item.product.id %>
<%= f.number_field :quantity, value: item.quantity.to_i%>
<%= f.submit "Actualizar carro de compras" %>
<%= link_to "Quitar productos", item, method: :delete, remote: true %>
<% end%>
<h2>Subtotal: $<%= item.total %></h2>
<% end %>

<h3>Tu pedido actual tiene un total de: $<%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
    <%= render 'cart_items'%>
</div>

<hr>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.heading %></td>
        <td><%= category.body %></td>
        <td><%= category.display %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @category.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @category.body %>
</p>

<p>
  <strong>Display:</strong>
  <%= @category.display %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_links.html.erb
<div class="col-2">

    <h5 class="link-container">
        <%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Menu", menu_path, class: "link #{@page == 'menu' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Catering", catering_path, class: "link #{@page == 'catering' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "More Info", info_path, class: "link #{@page == 'info' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Customer Reviews", "", class: "link #{@page == 'reviews' ? 'active' : ''}" %>
    </h5>


</div>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text">
        Food Bistro
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Food Bistro!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
</head>

<body>
    <% cache do %>
    <div class="<%= @page %>-page">
        <div class="row page-container">
            <%= render 'layouts/links'%>
            <div class="col-8">
                <% unless @page == "home"%>
                <%= render 'layouts/title'%>
                <% end %>
                <%= yield %>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <% end %>
</body>

</html>

app/views/menu/_products.html.erb
<div class="row">
    <% @cats.includes(:featured_products).each do |cat| %>
    <%# <% @cats.each do |cat| %> 
    <% if cat.featured_products.first.image.attached? %>
   <%#  <% if cat.products.where(featured: true).first.image.attached? %> 
    <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid')%>
    <% end %>
    <div class="col-12">
        <h1 style="text-align:center;"><%= cat.heading %>  </h1> 
        <hr />
    </div>
    <% @products.each do |product| %>
    <% if product.category == cat %>
    <div class="col-4">
        <h5>
            <%= product.name %> 
        </h5>
        
        <p>
            <%= product.description%>
        </p>
        <span>$<%= product.price %> <%= product.catering && product.available ? "| Disponible para delivery!" : "| Solo retiro en tienda" %></span>
            <% if product.available && product.catering == true  %>
                     <div id="menu-products-container">
                        <%= form_with model: @orders_item do |f| %>
                        <%= f.hidden_field :product_id, value: product.id %>
                        <%= f.number_field :quantity, value: 0, min: 1%>
                        <%= f.submit "Agregar al carro" %>
                        <% end %>
                    </div>
            
            <% end %>
            
    </div>
                                                 
    <% end %>
    
    <% end %>
    <hr />
    <% end %>
    
</div>

app/views/menu/index.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-12">
            <%= form_tag(search_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8 p-0">
                    <%= text_field_tag :search, '', class:'form-control', placeholder: 'Search...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4 p-0">
                    <%= select_tag "filter", options_for_select(['Filtrar por', 
                    'Sin lactosa', 
                    'Gluten Free',
                    'Vegana', 
                    'Vegetariana']), class:'custom-select', onchange:'clickSubmit()'%>
                    <%= submit_tag "Search", class:'d-none btn btn-danger', id:'search_submit'%>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <div id="menu-products-container">
        <%= render 'menu/products'%>
    </div>
</div>

<script>
    function clickSubmit() {
        $("#search_submit").click();
    }

</script>

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>");

app/views/orders_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>)");

app/views/orders_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/orders_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/pages/catering.html.erb
<h1>Pages#catering</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/home.html.erb
<div class="col-8"></div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :dairy_free %>
    <%= form.check_box :dairy_free %>
  </div>

  <div class="field">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free %>
  </div>

  <div class="field">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="field">
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="field">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="field">
    <%= form.label :category%>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :heading, @product.category.id) %>
  </div>

  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Dairy free</th>
      <th>Gluten free</th>
      <th>Vegan</th>
      <th>Vegetarian</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.dairy_free %></td>
        <td><%= product.gluten_free %></td>
        <td><%= product.vegan %></td>
        <td><%= product.vegetarian %></td>
        <td><%= product.available %></td>
        <td><%= product.catering %></td>
        <td><%= product.featured %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Dairy free:</strong>
  <%= @product.dairy_free %>
</p>

<p>
  <strong>Gluten free:</strong>
  <%= @product.gluten_free %>
</p>

<p>
  <strong>Vegan:</strong>
  <%= @product.vegan %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @product.vegetarian %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @product.catering %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @product.featured %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>